from contextlib import asynccontextmanager
from collections.abc import AsyncIterator
import os
import base64
from openai import OpenAI
from typing import Optional
from mcp.server.fastmcp import Context, FastMCP
from openai import AzureOpenAI


# Global constant for model name
# MODEL_NAME = "qwen-vl-max-2025-04-08"
# MODEL_NAME = "claude-opus-4-20250514"
# MODEL_NAME = "llama-4-maverick"
# MODEL_NAME = "gpt-4o"
# MODEL_NAME = "gpt-4.1"
MODEL_NAME = "o3"
# MODEL_NAME = "gemini-2.5-pro"
# MODEL_NAME = "gpt-5"

client = OpenAI(                                                            
    api_key="k",
    base_url="",
)

client = AzureOpenAI(
    azure_endpoint = "/",
    api_key='',
    api_version=""
)

def encode_image(image_path):
    """Convert image to base64 encoding"""
    try:
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')
    except Exception as e:
        print(f"Failed to load image: {str(e)}")
        return None


# Initialize message list to save conversation history
messages = []

# Lifecycle management
@asynccontextmanager
async def lifespan(app) -> AsyncIterator[None]:
    print("Starting Chat service...")
    try:
        yield
    finally:
        print("Shutting down Chat service...")

# Create FastMCP instance
mcp = FastMCP("ChatService", dependencies=["openai"], lifespan=lifespan, log_level='ERROR')
    

@mcp.tool()
def ask_with_images(ctx: Context, type_m: int, screenshot_image_path: Optional[str] = None, reference_image_path: Optional[str] = None) -> str:
    """
    Generate the next drawing instruction based on a reference image and/or current screenshot.
    
    Parameters:
    - ctx: Scientific illustration drawing context.
    - type_m: 1/2 (1 represents initial drawing, 2 represents continuing drawing).
    - screenshot_image_path: Path to the current screen screenshot (Optional).
    - reference_image_path: Path to the reference image (Optional).
    
    Returns:
    - Drawing instructions generated by the LLM.
    """
    
    t2i_image_caption_1 = "Create an illustration of a residual neural ..."
    ti2i_image_caption_1 = "The content of the scientific illustration is as follows: ..."

    # Image of the standard pixel coordinate system used in GUI automation
    

    # Prompt 1: Initial Drawing Instructions
    question_1 = (f"{t2i_image_caption_1}. You must design the image strictly according to this description without inventing any non-existent components. "
                f"Follow the requirements below and output your design steps. "
                f"Draw in detail; design the color scheme and fonts yourself. Ensure color harmony, font consistency, "
                f"and ensure fonts match the shape size and remain legible. "
                f"Your output must follow the structured format below. "
                f"****** WARNING: All elements must stay within coordinates 400 < x < 2000; 400 < y < 1300!!! ******"
                f"\n\n*** Full Module Drawing Example (Note: Text content can be included): ***"
                f"- **Shape:** Rectangle (Options: Rectangle, Circle, Cylinder, Cube, or any Closed Shape [Star, Triangle, Parallelogram, Trapezoid, Hexagon, etc.]. "
                f"Cylinder/Cube sizes are in mm; others are in pixels. 1mm ≈ 5 pixels)"
                f"- **Shape Start:** (-, -)"
                f"- **Shape Intermediate Points:** (-, -)(-, -)(-, -)(-, -) (Required only for custom closed shapes)"
                f"- **Shape End:** (-, -)"
                f"- **Fill:** Solid Fill (Options: No Fill, Solid Fill. ***Required item***)"
                f"- **Fill Color:** #FFD700 (16-bit hex color)"
                f"- **Fill Opacity:** -- (Range: 0-60)"
                f"- **Line Type:** Solid Line (Only Solid Line available)"
                f"- **Line Color:** #FFD700"
                f"- **Line Opacity:** -- (Range: 0-60, ***Do not exceed 60***)"
                f"- **Line Width:** -- (Range: 0-10)"
                f"- **Corner Radius:** --mm (Range: 0-10, must include 'mm' unit)"
                f"- **Text Content:** -- (Optional)"
                f"- **Font:** Comic Sans MS"
                f"- **Font Size:** -- (Range: 8-24)"
                f"- **Font Color:** #FFD700"
                f"- **Font Style:** Italic (Options: Italic, Non-Italic)"
                f"- **Font Weight:** Bold (Options: Bold, Non-Bold)"
                f"\n\n*** Full Line Drawing Example (Note: No text allowed here; add text using the text tool): ***"
                f"- **Shape:** Straight Line (Options: Straight Line, Curve, Continuous Line)"
                f"- **Line Start:** (-, -)"
                f"- **Line Intermediate Points:** (-, -) (Required for curves or continuous lines)"
                f"- **Line End:** (-, -)"
                f"- **Line Type:** Solid Line"
                f"- **Line Color:** #FFD700"
                f"- **Line Opacity:** -- (Range: 0-60)"
                f"- **Line Width:** -- (Range: 0-10)"
                f"- **Corner Radius:** --mm"
                f"- **Arrow:** Arrow (Options: Arrow, No Arrow)"
                f"\n\n*** Full Independent Text Example: ***"
                f"- **Text Position:** (-, -)"
                f"- **Text Box Size:** (-, -)"
                f"- **Text Content:** --"
                f"- **Font:** Comic Sans MS"
                f"- **Font Size:** --"
                f"- **Font Color:** #FFD700"
                f"- **Font Style:** Italic"
                f"- **Font Weight:** Bold"
                f"\n\nNote: Output text content only in English. Font must be 'Comic Sans MS'. Arrange text box and font size reasonably. "
                f"Design in steps: Output only 1-3 components (modules, lines, text) per step. "
                f"If an image is provided, treat it as a reference. You have 100% autonomy in design. "
                f"Keep all drawings within 400 < x < 2000; 400 < y < 1300. Control sizes and spacing reasonably. "
                f"*** Output the above design content in Chinese. ***")
    
    # Prompt 2: Continuation Drawing Instructions
    question_2 = (f"{t2i_image_caption_1}"
                f"The first image is the result of the current design. Analyze the gap between current progress and the final goal, then design the next steps. "
                f"The previous steps are finished. If a second image is provided, it is the target reference image. "
                f"Analyze the drawn content carefully; there is no need to correct previous mistakes, just move forward. "
                f"If completed, output '全部结束' (All Finished) and only those four words. "
                f"In addition to drawing tools, you can modify elements: Resize, Copy, Move, or Delete. "
                f"Example: Change size of element at (-,-) within range (-,-) to (-,-); Move element at (-,-) within range (-,-) to (-,-). "
                f"***Note:*** Use the geometric center of the target module for coordinates. "
                f"You can also add creative icons: chatgpt, correct, deepseek, error, fire, image, qwen, snow, text, robot, light, gear, network, book, medal. "
                f"*** Icon Insert Example: ***"
                f"- **Type:** icon"
                f"- **Icon Name:** gear"
                f"- **Position:** (-, -)"
                f"- **Size:** (-, -) (Width and Height in mm; 1mm ≈ 5 pixels)."
                f"\n\nOne step must only output 1-3 components. Maintain the original output paradigm. "
                f"Maintain the range 400 < x < 2000; 400 < y < 1300. Do not invent info; follow the description strictly. "
                f"*** Output the above design content in Chinese. ***")
    
    global messages 

    if str(type_m) == "1":  # Initial drawing detected
        messages = []  # Clear global history
        print("Initial drawing detected, message list cleared.")
    
    if len(messages) == 0:
        question = question_1
    else:
        question = question_2
    
    # Combined problem description
    full_question = question

    # Add screenshot status
    if screenshot_image_path:
        base64_screenshot_image = encode_image(screenshot_image_path)
        if base64_screenshot_image:
            full_question += "\n\nCurrent screenshot provided."
        else:
            full_question += "\n\nScreenshot failed to load."
    else:
        full_question += "\n\nNo screenshot provided, generating instructions from initial state."

    # Add reference image status
    if reference_image_path:
        base64_reference_image = encode_image(reference_image_path)
        if base64_reference_image:
            full_question += "\n\nReference image provided."
        else:
            full_question += "\n\nReference image failed to load."
    else:
        full_question += "\n\nNo reference image provided, free design mode active."

    # Build message content
    content = [{"type": "text", "text": full_question}]

    if screenshot_image_path and base64_screenshot_image:
        content.append({
            "type": "image_url", 
            "image_url": {
                "url": f"data:image/jpeg;base64,{base64_screenshot_image}",
                "alt_text": "Current Drawing Progress"
            }
        })

    if reference_image_path and base64_reference_image:
        content.append({
            "type": "image_url", 
            "image_url": {
                "url": f"data:image/jpeg;base64,{base64_reference_image}",
                "alt_text": "Reference Image (Target Effect)"
            }
        })

    # Send request
    user_message = {"role": "user", "content": content}
    
    try:
        completion = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages + [user_message]
        )
        assistant_reply = completion.choices[0].message.content

        # Extract only text for history (to save tokens/limit)
        text_only_user_content = [item for item in content if item["type"] == "text"]

        # Append history
        messages.append({"role": "user", "content": text_only_user_content})
        messages.append({"role": "assistant", "content": [{"type": "text", "text": assistant_reply}]})

        # Keep last 96 messages (approx 48 rounds)
        if len(messages) > 96:
            messages = messages[-96:]

        return assistant_reply
    except Exception as e:
        return f"Request Error: {str(e)}"

if __name__ == "__main__":
    mcp.run(transport='stdio')